apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-testing-app
  namespace: argo-testing
  labels:
    app: argo-testing-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-testing-app
  template:
    metadata:
      labels:
        app: argo-testing-app
    spec:
      containers:
      - name: argo-testing-app
        image: nginx
        ports:
        - containerPort: 80

